apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission
  namespace: transmission-openvpn
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: transmission-openvpn-transmission-auth-chain@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - secretName: transmission-tls-secret
      hosts:
        - transmission.baphomet.cloud
  rules:
    - host: transmission.baphomet.cloud
      http:
        paths:

          # oauth2-proxy endpoints (NO AUTH)
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: oauth2-proxy
                port:
                  number: 4180

          # Transmission UI (AUTH REQUIRED)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transmission-openvpn
                port:
                  number: 9091
