apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transmission-root-redirect
  namespace: transmission-openvpn
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: transmission-openvpn-transmission-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: transmission.baphomet.cloud
    http:
      paths:
      - path: /
        pathType: Exact # Exact match for the root only
        backend:
          service:
            name: transmission-openvpn # Just a placeholder, middleware handles the redirect
            port:
              number: 9091