apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: transmission-openvpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
        ports:
        - containerPort: 4180
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: OAUTH2_PROXY_CLIENT_ID
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: OAUTH2_PROXY_CLIENT_SECRET
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: OAUTH2_PROXY_COOKIE_SECRET
        args:
          - --provider=github
          - --github-user=muchasxmaracas
          - --http-address=0.0.0.0:4180
          - --email-domain=*
          - --cookie-domain=.baphomet.cloud
          - --cookie-secure=true
          - --cookie-httponly=true
          - --cookie-samesite=lax
          - --cookie-refresh=1h
          - --upstream=http://transmission-openvpn:9091
          - --redirect-url=https://transmission.baphomet.cloud/oauth2/callback
          - --whitelist-domain=.baphomet.cloud
          - --set-xauthrequest=true
          - --skip-provider-button=false
          - --auth-logging=true
          - --request-logging=true
          - --standard-logging=true
          - --reverse-proxy=true
          - --scope=user:email
          
        resources:
          requests:
            cpu: 25m
            memory: 250Mi
          limits:
            cpu: 25m
            memory: 250Mi

