apiVersion: v1
kind: ConfigMap
metadata:
  name: pelican-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.panel.extraEnv.APP_ENV | default "production" | quote }}
  APP_DEBUG: {{ .Values.panel.extraEnv.APP_DEBUG | default "false" | quote }}
  APP_URL: {{ .Values.panel.extraEnv.APP_URL | quote }}
  APP_TIMEZONE: {{ .Values.panel.extraEnv.TIMEZONE | default "UTC" | quote }}
  APP_EMAIL: {{ .Values.panel.extraEnv.APP_EMAIL | quote }}
  CADDY_SERVER_ADMIN_EMAIL: {{ .Values.panel.extraEnv.CADDY_SERVER_ADMIN_EMAIL | quote }}
  LE_EMAIL: {{ .Values.panel.extraEnv.APP_EMAIL | default "sandromarton95@gmail.com" | quote }}
  # Database connection info (mapped to service name)
  DB_HOST: {{ .Values.database.config.host | quote }}
  DB_PORT: {{ .Values.database.config.port | quote }}
  DB_DATABASE: {{ .Values.database.config.database | quote }}
  DB_USERNAME: {{ .Values.database.config.user | quote }}