apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pelican
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-pelican-headers@kubernetescrd
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: pelican
            port:
              name: http