affinity: {}

# Persistence for config and data
persistence:
  config:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    storageClass: hcloud-volumes
  data:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 100Gi
    storageClass: storage-box-1

# Environment variables for VPN and Network
env:
  TRANSMISSION_WEB_UI: "transmissionic"
  TRANSMISSION_RPC_USERNAME: "admin"
  TRANSMISSION_RPC_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: transmission-ui-auth
        key: password
  TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
  OPENVPN_PROVIDER: "PIA"
  OPENVPN_CONFIG: "france"
  OPENVPN_USERNAME: "p2746337"
  OPENVPN_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: transmission-vpn-auth
        key: password
  LOCAL_NETWORK: "192.168.0.0/16"

image:
  repository: haugene/transmission-openvpn
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []

ingress:
  enabled: true
  ingressClassName: 'traefik'
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  hosts:
    - host: transmission.baphomet.cloud
      paths:
        - path: /transmission/web/
          pathType: ImplementationSpecific
        - path: /transmission/rpc
          pathType: ImplementationSpecific
  tls:
    - secretName: transmission-tls-secret
      hosts:
        - transmission.baphomet.cloud

podAnnotations: {}
podLabels: {}

# Critical for VPN: Needs NET_ADMIN capability
podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    add:
      - NET_ADMIN
  privileged: false
  runAsNonRoot: false # Often required for OpenVPN to initialize tun device
  runAsUser: 0 

service:
  type: ClusterIP
  port: 9091

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 512Mi

# Add this to your values.yaml
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "transmission-openvpn"

nodeSelector: {}
tolerations: []